"use client";
import {useEffect,useMemo,useState} from "react";
import {BookOpen,Flame,Globe2,Leaf,ArrowRight,X,ScrollText,Compass,ShieldCheck} from "lucide-react";
import {initialConfessions,type Confession} from "@/data/content";
import {garudaJourney,narakaEntries} from "@/data/naraka";
import {copy,productLanguages,type ProductLanguage} from "@/data/i18n";

type Page="ledger"|"garuda"|"dharma"|"about";
type Verdict={confession:Confession;choice:"punya"|"paapa"}|null;
const categories={en:["Petty Sin","Career","Love","Regret","Deep Secret"],te:["చిన్న తప్పు","వృత్తి","ప్రేమ","పశ్చాత్తాపం","లోతైన రహస్యం"],hi:["छोटी भूल","करियर","प्रेम","पश्चाताप","गहरा रहस्य"],ta:["சிறு தவறு","வேலை","காதல்","வருத்தம்","ஆழ்ந்த ரகசியம்"],kn:["ಸಣ್ಣ ತಪ್ಪು","ವೃತ್ತಿ","ಪ್ರೀತಿ","ಪಶ್ಚಾತ್ತಾಪ","ಆಳವಾದ ರಹಸ್ಯ"],ml:["ചെറിയ തെറ്റ്","തൊഴിൽ","പ്രണയം","പശ്ചാത്താപം","ആഴത്തിലുള്ള രഹസ്യം"],mr:["किरकोळ चूक","करिअर","प्रेम","पश्चात्ताप","गुपित"],bn:["ছোট ভুল","কর্মজীবন","ভালোবাসা","অনুতাপ","গভীর গোপন"]} as const;

export default function ChithragupthaApp(){
 const [language,setLanguage]=useState<ProductLanguage>("en");const [page,setPage]=useState<Page>("ledger");const [confessions,setConfessions]=useState(initialConfessions);const [voted,setVoted]=useState<Record<number,"punya"|"paapa">>({});const [text,setText]=useState("");const [category,setCategory]=useState(0);const [verdict,setVerdict]=useState<Verdict>(null);const [toast,setToast]=useState("");const t=copy[language];const cats=categories[language];
 useEffect(()=>{const saved=window.localStorage.getItem("cg-language") as ProductLanguage|null;if(saved&&copy[saved])setLanguage(saved)},[]);
 function changeLanguage(next:ProductLanguage){setLanguage(next);window.localStorage.setItem("cg-language",next);document.documentElement.lang=next}
 function go(p:Page){setPage(p);window.scrollTo({top:0,behavior:"smooth"})}
 function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),1800)}
 function record(){const value=text.trim();if(!value){notify(t.placeholder);return}setConfessions(c=>[{id:Date.now(),text:value,category:categories.en[category],time:"just now",punya:0,paapa:0,soul:`#${Math.floor(100+Math.random()*899)}`},...c]);setText("");notify(t.record)}
 function vote(id:number,choice:"punya"|"paapa"){if(voted[id])return;const item=confessions.find(x=>x.id===id);if(!item)return;const updated={...item,[choice]:item[choice]+1};setVoted(v=>({...v,[id]:choice}));setConfessions(c=>c.map(x=>x.id===id?updated:x));setVerdict({confession:updated,choice})}
 function randomSoul(){const item=confessions[Math.floor(Math.random()*confessions.length)];document.getElementById(`soul-${item.id}`)?.scrollIntoView({behavior:"smooth",block:"center"});notify(t.random)}
 const stats=useMemo(()=>({recorded:1284+Math.max(0,confessions.length-initialConfessions.length),votes:9731+Object.keys(voted).length}),[confessions.length,voted]);
 return <div className="cg-shell"><header className="cg-header"><div className="cg-brand"><div className="cg-lamp">🪔</div><div><div className="cg-eyebrow">The Cosmic Ledger</div><div className="cg-title">Chithraguptha</div><div className="cg-tagline cg-muted">{t.tagline}</div></div></div><div className="cg-header-tools"><label className="cg-language"><Globe2 size={14}/><span>{t.language}</span><select value={language} onChange={e=>changeLanguage(e.target.value as ProductLanguage)} aria-label={t.language}>{Object.entries(productLanguages).map(([code,l])=><option value={code} key={code}>{l.native}</option>)}</select></label><nav className="cg-nav">{(["ledger","garuda","dharma","about"] as Page[]).map(p=><button key={p} className={page===p?"active":""} onClick={()=>go(p)}>{p==="ledger"?t.ledger:p==="garuda"?t.garuda:p==="dharma"?t.dharma:t.about}</button>)}</nav></div></header><main className="cg-main">
 {page==="ledger"&&<><section className="cg-hero"><div className="cg-hero-mark">🪔</div><div className="cg-eyebrow">{t.heroEyebrow}</div><h1>{t.heroTitle}</h1><p>{t.heroBody}</p><div className="cg-actions"><button className="cg-primary" onClick={()=>document.getElementById("composer")?.scrollIntoView({behavior:"smooth"})}><ScrollText size={16}/>{t.enter}</button><button className="cg-secondary" onClick={randomSoul}><Compass size={16}/>{t.random}</button></div><div className="cg-hero-trust"><span><ShieldCheck size={14}/>{t.anonymous}</span><span><BookOpen size={14}/>{t.sacredNote}</span></div></section><section className="cg-stats"><div className="cg-stat"><b>{stats.recorded.toLocaleString()}</b><span>{t.recorded}</span></div><div className="cg-stat"><b>{stats.votes.toLocaleString()}</b><span>{t.judgments}</span></div><div className="cg-stat"><b>842</b><span>{t.visited}</span></div></section><section className="cg-composer" id="composer"><div className="cg-composer-heading"><div><div className="cg-eyebrow">{t.recordEyebrow}</div><h2 className="cg-section-title">{t.confession}</h2></div><span className="cg-seal">CONFIDENTIAL</span></div><textarea className="cg-textarea" maxLength={500} value={text} onChange={e=>setText(e.target.value)} placeholder={t.placeholder}/><div className="cg-counter">{text.length} / 500</div><div className="cg-compose-row"><select className="cg-select" value={category} onChange={e=>setCategory(Number(e.target.value))}>{cats.map((c,i)=><option value={i} key={c}>{c}</option>)}</select><button className="cg-primary" onClick={record}>{t.record}<ArrowRight size={15}/></button></div></section><section className="cg-ledger-intro"><div><div className="cg-eyebrow">{t.community}</div><h2>{t.today}</h2></div><p className="cg-note">{t.atlasBody}</p></section><div className="cg-feed">{confessions.map(item=>{const choice=voted[item.id];return <article className="cg-card" id={`soul-${item.id}`} key={item.id}><div className="cg-meta"><span className="cg-pill">{item.category}</span><span className="cg-time">{item.time}</span></div><div className="cg-confession">{item.text}</div><div className="cg-soul">Soul {item.soul}</div><div className="cg-reactions"><button disabled={!!choice} className={`cg-react green ${choice==="punya"?"selected":""}`} onClick={()=>vote(item.id,"punya")}><Leaf size={16}/><b>Punya</b><span>{item.punya}</span></button><button disabled={!!choice} className={`cg-react red ${choice==="paapa"?"selected":""}`} onClick={()=>vote(item.id,"paapa")}><Flame size={16}/><b>Paapa</b><span>{item.paapa}</span></button></div>{choice&&<div className="cg-micro">{t.reflection}: {choice==="punya"?"Punya":"Paapa"}. Opposite judgment disabled.</div>}</article>})}</div></>}
 {page==="garuda"&&<GarudaPage t={t}/>} {page==="dharma"&&<DharmaPage t={t}/>} {page==="about"&&<AboutPage t={t}/>}<footer className="cg-footer">{t.company}</footer></main>
 {verdict&&<div className="cg-modal" role="dialog" aria-modal="true"><div className="cg-modal-box"><button className="cg-close" onClick={()=>setVerdict(null)} aria-label={t.close}><X size={20}/></button><div className="cg-eyebrow">{t.verdict}</div><h2 style={{font:"30px Georgia,serif",margin:"4px 0 15px"}}>{t.consequence}</h2><p className="cg-note">{t.reflection}: <b>{verdict.choice==="punya"?"Punya":"Paapa"}</b></p><div className="cg-panel" style={{marginTop:12,padding:14}}><p style={{font:"21px Georgia,serif"}}>{t.repair}</p><p className="cg-note">{t.vision}</p></div><button className="cg-primary" style={{marginTop:12}} onClick={()=>setVerdict(null)}>{t.close}</button></div></div>}{toast&&<div className="cg-toast">{toast}</div>}</div>
}
function GarudaPage({t}:{t:typeof copy.en}){return <section><div className="cg-page-title"><div className="cg-eyebrow">Preta-mārga · Yama-mārga · Naraka</div><h1>{t.garuda}</h1><p className="cg-note">{t.sourceNote}</p></div><div className="cg-lore-hero"><img src="/lore/garuda-vishnu.svg" alt="Garuda and Vishnu manuscript-inspired illustration"/><div><div className="cg-eyebrow">{t.journey}</div><h2>Garuda Purāṇa: a journey of karma and consequence</h2><p>{t.heroBody}</p></div></div><div className="cg-panel cg-lore-panel"><div className="cg-source-banner"><BookOpen size={17}/><span>{t.sacredNote}</span></div><div className="cg-section-title"><div className="cg-eyebrow">{t.journey}</div><h2>The journey beyond death</h2></div><div className="cg-grid3">{garudaJourney.map((x,i)=><div className="cg-mini" key={x.title}><div className="cg-eyebrow">0{i+1}</div><h3>{x.title}</h3><p>{x.detail}</p></div>)}</div></div><div className="cg-section-title cg-atlas-heading"><div className="cg-eyebrow">{t.atlas}</div><h2>Traditional Naraka Atlas</h2><p className="cg-note">{t.atlasBody}</p></div><div className="cg-naraka-card-grid">{narakaEntries.map((n,i)=>{const image=i%3===0?"/lore/vaitarani.svg":i%3===1?"/lore/chitragupta-ledger.svg":"/lore/garuda-vishnu.svg";return <article className="cg-naraka-card" key={n.name}><div className="cg-naraka-image"><img src={image} alt={`${n.name} — ${n.meaning}`}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="cg-naraka-card-content"><div className="cg-eyebrow">{n.sanskrit}</div><h3>{n.name}</h3><p className="cg-naraka-meaning">{n.meaning}</p><div className="cg-naraka-section"><strong>{t.traditional}</strong><p>{n.association}</p></div><div className="cg-naraka-section"><strong>{t.experience}</strong><p>{n.experience}</p></div><div className="cg-remedy"><strong>🌿 {t.lesson}</strong><p>{n.lesson}</p></div><div className="cg-source">{t.source}: {n.source}{n.caution?` · ${n.caution}`:""}</div></div></article>})}</div></section>}
function DharmaPage({t}:{t:typeof copy.en}){const cards=[["Satya","Truth","Correct the lie. Admit the mistake. Restore truth."],["Dama","Self-restraint","Interrupt the pattern before desire becomes harm."],["Seva","Service","Turn remorse into useful action without seeking reward."],["Dāna","Generosity","Give responsibly where generosity genuinely helps."],["Prāyaścitta","Atonement","Where tradition prescribes atonement, show its source and context."],["Bhakti","Devotion","Prayer and remembrance can accompany concrete repair."]];return <section><div className="cg-page-title"><div className="cg-eyebrow">Karma · Dharma · Prāyaścitta</div><h1>{t.dharma}</h1><p className="cg-note">{t.vision}</p></div><div className="cg-lore-hero"><img src="/lore/chitragupta-ledger.svg" alt="Cosmic ledger illustration"/><div><div className="cg-eyebrow">{t.repair}</div><h2>Record → Reflect → Repair → Remember</h2><p>{t.company}</p></div></div><div className="cg-grid2">{cards.map(([a,b,c])=><div className="cg-mini" key={a}><div className="cg-eyebrow">{a}</div><h3>{b}</h3><p>{c}</p></div>)}</div></section>}
function AboutPage({t}:{t:typeof copy.en}){return <section><div className="cg-page-title"><div className="cg-eyebrow">{t.aboutEyebrow}</div><h1>{t.aboutTitle}</h1><p className="cg-note">{t.aboutIntro}</p></div><div className="cg-panel" style={{padding:20}}><div className="cg-grid2"><div><div className="cg-eyebrow">{t.visionTitle}</div><h2>{t.visionTitle}</h2><p>{t.vision}</p></div><div><div className="cg-eyebrow">{t.companyTitle}</div><h2>{t.companyTitle}</h2><p>{t.company}</p></div></div></div><div className="cg-section-title"><div className="cg-eyebrow">{t.principlesTitle}</div><h2>{t.principlesTitle}</h2></div><div className="cg-grid2">{t.principles.map((p,i)=><div className="cg-mini" key={i}><div className="cg-eyebrow">0{i+1}</div><p>{p}</p></div>)}</div><div className="cg-remedy" style={{marginTop:14}}><strong>{t.responsibleTitle}</strong><p>{t.responsible}</p><small>{t.sacredNote}</small></div></section>}
