"use client";
import {useMemo,useState} from "react";
import {ArrowRight,BookOpen,ChevronDown,Flame,Globe2,Leaf,ScrollText,Sparkles,X} from "lucide-react";
import {initialConfessions,type Confession} from "@/data/content";
import {garudaJourney,narakaEntries} from "@/data/naraka";
import {languages,ui,type LanguageCode} from "@/data/languages";

type Page="ledger"|"garuda"|"dharma"; type Verdict={confession:Confession;choice:"punya"|"paapa"}|null;
const categoryNames={en:["Petty Sin","Career","Love","Regret","Deep Secret"],te:["చిన్న తప్పు","వృత్తి","ప్రేమ","పశ్చాత్తాపం","లోతైన రహస్యం"],hi:["छोटी भूल","करियर","प्रेम","पश्चाताप","गहरा रहस्य"],ta:["சிறு தவறு","வேலை","காதல்","வருத்தம்","ஆழ்ந்த ரகசியம்"],kn:["ಸಣ್ಣ ತಪ್ಪು","ವೃತ್ತಿ","ಪ್ರೀತಿ","ಪಶ್ಚಾತ್ತಾಪ","ಆಳವಾದ ರಹಸ್ಯ"],ml:["ചെറിയ തെറ്റ്","തൊഴിൽ","പ്രണയം","പശ്ചാത്താപം","ആഴത്തിലുള്ള രഹസ്യം"],mr:["किरकोळ चूक","करिअर","प्रेम","पश्चात्ताप","गुपित"],bn:["ছোট ভুল","কর্মজীবন","ভালোবাসা","অনুতাপ","গভীর গোপন"]} as const;
const sourceNote="The famous 28-Naraka catalogue is especially explicit in Bhāgavata Purāṇa 5.26 and appears with variants across Purāṇic literature. Garuda Purāṇa's Preta material independently discusses Yama-mārga, Chitragupta, Yamadutas, Naraka and post-death consequences. This atlas is comparative, not a claim that every mapping belongs uniquely to one edition of Garuda Purāṇa.";

export default function LedgerAppV2(){
 const [page,setPage]=useState<Page>("ledger"); const [language,setLanguage]=useState<LanguageCode>("en"); const [confessions,setConfessions]=useState(initialConfessions); const [voted,setVoted]=useState<Record<number,"punya"|"paapa">>({}); const [text,setText]=useState(""); const [category,setCategory]=useState(0); const [verdict,setVerdict]=useState<Verdict>(null); const [toast,setToast]=useState("");
 const t=ui[language]; const categories=categoryNames[language]; const votes=Object.keys(voted).length; const stats=useMemo(()=>({confessions:1284+Math.max(0,confessions.length-initialConfessions.length),votes:9731+votes}),[confessions.length,votes]);
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),1800)};
 function record(){const clean=text.trim();if(!clean){notify("The Ledger awaits your confession.");return}const item:Confession={id:Date.now(),text:clean,category:categoryNames.en[category],time:"just now",punya:0,paapa:0,soul:`#${Math.floor(100+Math.random()*899)}`};setConfessions(c=>[item,...c]);setText("");notify("Your deed has been recorded.")}
 function vote(id:number,choice:"punya"|"paapa"){if(voted[id])return;const item=confessions.find(x=>x.id===id);if(!item)return;const updated={...item,[choice]:item[choice]+1};setVoted(v=>({...v,[id]:choice}));setConfessions(c=>c.map(x=>x.id===id?updated:x));setVerdict({confession:updated,choice})}
 function randomSoul(){const target=confessions[Math.floor(Math.random()*confessions.length)];document.getElementById(`confession-${target.id}`)?.scrollIntoView({behavior:"smooth",block:"center"});notify("The Ledger opened a random soul.")}
 function showPage(p:Page){setPage(p);window.scrollTo({top:0,behavior:"smooth"})}
 return <div className="cg-shell" dir={languages[language].dir}>
  <header className="cg-header"><div className="cg-brand"><div className="cg-lamp">🪔</div><div><div className="cg-eyebrow">The Cosmic Ledger</div><div className="cg-title">Chithraguptha</div><div className="cg-tagline cg-muted">Confess. Be witnessed. Reflect on karma.</div></div></div>
   <div className="cg-header-tools"><label className="cg-language"><Globe2 size={14}/><span>{t.language}</span><select value={language} onChange={e=>setLanguage(e.target.value as LanguageCode)} aria-label={t.language}>{Object.entries(languages).map(([code,l])=><option value={code} key={code}>{l.native}</option>)}</select></label><nav className="cg-nav">{(["ledger","garuda","dharma"] as Page[]).map(p=><button key={p} className={page===p?"active":""} onClick={()=>showPage(p)}>{p==="ledger"?t.ledger:p==="garuda"?t.garuda:t.dharma}</button>)}</nav></div>
  </header>
  <main className="cg-main">
   {page==="ledger"&&<>
    <section className="cg-hero"><div className="cg-eyebrow">न किञ्चिद् विस्मृतम् · Nothing forgotten</div><h1>What would you place before Chitragupta?</h1><p>An anonymous space for confession, reflection and community response — inspired by the cultural imagination of Chitragupta, karma and dharma.</p><div className="cg-actions"><button className="cg-primary" onClick={()=>document.getElementById("composer")?.scrollIntoView({behavior:"smooth"})}>Enter your confession</button><button className="cg-secondary" onClick={randomSoul}>🔮 {t.random}</button></div></section>
    <section className="cg-stats"><div className="cg-stat"><b>{stats.confessions.toLocaleString()}</b><span>deeds recorded</span></div><div className="cg-stat"><b>{stats.votes.toLocaleString()}</b><span>judgments passed</span></div><div className="cg-stat"><b>842</b><span>souls visited</span></div></section>
    <section id="composer" className="cg-composer"><div className="cg-eyebrow">Record a deed</div><h2 className="cg-section-title">{t.confession}</h2><textarea className="cg-textarea" maxLength={500} value={text} onChange={e=>setText(e.target.value)} placeholder={t.placeholder}/><div className="cg-counter">{text.length} / 500</div><div className="cg-compose-row"><select className="cg-select" value={category} onChange={e=>setCategory(Number(e.target.value))}>{categories.map((c,i)=><option value={i} key={c}>{c}</option>)}</select><button className="cg-primary" onClick={record}>{t.record} <ArrowRight size={15} style={{verticalAlign:"middle"}}/></button></div><div className="cg-note" style={{marginTop:8}}>No name. No email. No login. Your public identity is a random Soul ID.</div></section>
    <section className="cg-section-title"><div className="cg-eyebrow">{t.judgment}</div><h2>{t.today}</h2></section><div className="cg-discover"><div><b>🔮 {t.random}</b><small>Skip the ranking. See what the Ledger serves next.</small></div><button className="cg-secondary" onClick={randomSoul}>Open →</button></div>
    <div className="cg-feed">{confessions.map(item=>{const selection=voted[item.id];return <article className="cg-card" id={`confession-${item.id}`} key={item.id}><div className="cg-meta"><span className="cg-pill">{item.category}</span><span className="cg-time">{item.time}</span></div><div className="cg-confession">{item.text}</div><div className="cg-soul">Soul {item.soul}</div><div className="cg-reactions"><button disabled={Boolean(selection)} className={`cg-react green ${selection==="punya"?"selected":""}`} onClick={()=>vote(item.id,"punya")}><Leaf size={16}/> <b>Punya</b> <span>{item.punya}</span></button><button disabled={Boolean(selection)} className={`cg-react red ${selection==="paapa"?"selected":""}`} onClick={()=>vote(item.id,"paapa")}><Flame size={16}/> <b>Paapa</b> <span>{item.paapa}</span></button></div>{selection&&<div className="cg-micro">Your judgment is recorded. Opposite judgment disabled.</div>}</article>})}</div>
   </>}
   {page==="garuda"&&<section><div className="cg-page-title"><div className="cg-eyebrow">Preta-mārga · Yama-mārga · Naraka</div><h1>{t.garuda}</h1><p className="cg-note">A respectful, source-aware exploration of the after-death material associated with the Garuda Purana and related Purāṇic traditions.</p></div>
    <div className="cg-lore-hero"><img src="/lore/garuda-vishnu.svg" alt="Stylized manuscript-inspired depiction of Vishnu and Garuda"/><div><div className="cg-eyebrow">The conversation</div><h2>Garuda asks. Vishnu explains.</h2><p>The Garuda Purana is not simply a catalogue of hell. Its wider material addresses death, rites, the preta's journey, karma, rebirth, dharma, merit and liberation. The frightening imagery is one part of a much larger religious and literary world.</p></div></div>
    <div className="cg-panel" style={{padding:18}}><div className="cg-source-banner"><BookOpen size={17}/><span>{sourceNote}</span></div><div className="cg-section-title"><div className="cg-eyebrow">The journey</div><h2>From death to consequence</h2></div><div className="cg-grid3">{garudaJourney.map((x,i)=><div className="cg-mini" key={x.title}><div className="cg-eyebrow">0{i+1}</div><h3>{x.title}</h3><p>{x.detail}</p></div>)}</div></div>
    <div className="cg-section-title"><div className="cg-eyebrow">Naraka Atlas</div><h2>28 traditional motifs</h2><p className="cg-note">Each entry separates the traditional association, the narrative experience and the ethical reflection. This is not a literal prediction engine.</p></div>
    <div className="cg-naraka-grid">{narakaEntries.map((n,i)=><details className="cg-naraka" key={n.name}><summary><span className="cg-naraka-num">{String(i+1).padStart(2,"0")}</span><span><b>{n.name}</b><small>{n.meaning} · {n.sanskrit}</small></span><ChevronDown size={17}/></summary><div className="cg-naraka-body"><div className="cg-naraka-columns"><div><div className="cg-eyebrow">Traditional association</div><p>{n.association}</p></div><div><div className="cg-eyebrow">Narrative experience</div><p>{n.experience}</p></div></div><div className="cg-remedy"><strong>🌿 Dharma reflection</strong><p>{n.lesson}</p></div><div className="cg-source">Source note: {n.source}{n.caution?` · ${n.caution}`:""}</div></div></details>)}</div>
   </section>}
   {page==="dharma"&&<section><div className="cg-page-title"><div className="cg-eyebrow">Karma · Dharma · Prāyaścitta</div><h1>Dharma Library</h1><p className="cg-note">The product's central idea is not “you are doomed.” It is “what do you do after seeing the consequence?”</p></div><div className="cg-lore-hero"><img src="/lore/chitragupta-ledger.svg" alt="Stylized cosmic ledger illustration"/><div><div className="cg-eyebrow">The Chithraguptha principle</div><h2>Record → Reflect → Repair → Remember</h2><p>Use the mythology as a mirror for conduct, not as a machine that claims authority over a person's spiritual destiny.</p></div></div><div className="cg-grid2"><div className="cg-mini"><div className="cg-eyebrow">Satya</div><h3>Truth</h3><p>Correct the lie. Admit the mistake. Restore the truth where it matters.</p></div><div className="cg-mini"><div className="cg-eyebrow">Dama</div><h3>Self-restraint</h3><p>Understand the trigger, interrupt the pattern and practice restraint.</p></div><div className="cg-mini"><div className="cg-eyebrow">Seva</div><h3>Service</h3><p>Turn remorse into useful action without treating service as a transaction for “karma points”.</p></div><div className="cg-mini"><div className="cg-eyebrow">Dāna</div><h3>Generosity</h3><p>Give responsibly and freely where generosity genuinely helps.</p></div><div className="cg-mini"><div className="cg-eyebrow">Prāyaścitta</div><h3>Atonement</h3><p>Where a tradition prescribes repentance or atonement, show the source and context rather than inventing a universal ritual.</p></div><div className="cg-mini"><div className="cg-eyebrow">Bhakti</div><h3>Devotion</h3><p>For devotional users, prayer and remembrance can accompany concrete repair rather than replace it.</p></div></div></section>}
   <footer className="cg-footer">Inspired by Hindu / Sanatana Dharma traditions. Chithraguptha is a mythology-inspired community experience, not a religious authority.</footer>
  </main>
  {verdict&&<div className="cg-modal" role="dialog" aria-modal="true"><div className="cg-modal-box"><button className="cg-close" onClick={()=>setVerdict(null)} aria-label="Close"><X size={20}/></button><div className="cg-eyebrow">{t.verdict}</div><h2 style={{font:"30px Georgia,serif",margin:"4px 0 15px"}}>The Ledger has spoken.</h2><p className="cg-note">Your judgment entered the Ledger as <b>{verdict.choice==="punya"?"Punya":"Paapa"}</b>.</p><div className="cg-meter"><div className="p" style={{width:`${Math.round(verdict.confession.punya/Math.max(1,verdict.confession.punya+verdict.confession.paapa)*100)}%`}}/><div className="q" style={{flex:1}}/></div><div className="cg-grid2" style={{marginTop:12}}><div className="cg-mini"><div className="cg-eyebrow">Punya</div><h3>{verdict.confession.punya}</h3></div><div className="cg-mini"><div className="cg-eyebrow">Paapa</div><h3>{verdict.confession.paapa}</h3></div></div><div className="cg-panel" style={{marginTop:12,padding:14}}><div className="cg-eyebrow">Reflection</div><p style={{font:"21px Georgia,serif"}}>The Ledger records. You choose what happens next.</p><p className="cg-note">This is a mythology-inspired interpretation, not a literal judgment by Chitragupta or a prediction of anyone's afterlife.</p></div><div className="cg-remedy"><strong>🌿 {t.repair}</strong><p>Acknowledge the action, understand who was affected, repair the harm where possible, and avoid repeating the pattern.</p></div><div className="cg-actions"><button className="cg-primary" onClick={()=>setVerdict(null)}>Continue reading</button><button className="cg-secondary" onClick={()=>{setVerdict(null);showPage("garuda")}}>{t.explore}</button></div></div></div>}
  {toast&&<div className="cg-toast" aria-live="polite">{toast}</div>}
 </div>
}
